import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  detail,
}: Readonly<{
  children: React.ReactNode;
  detail: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col p-24">
          <h1 className="text-2xl font-bold my-4">Textkernel Search</h1>
          <div className="grid grid-cols-2 gap-x-4">
            <div className="col-span-1">{children}</div>
            <div className="col-span-1">{detail}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
